spring.application.name=nino-costero-backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ninocostero
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=ALTER USER postgres PASSWORD 'postgres';

# Fechas en formato ISO-8601 (no epoch)
spring.jackson.serialization.write-dates-as-timestamps=false
